### ISSUE TITLE
Improve TBL DAT parsing

### ISSUE THREAD

**Issue by JasonBrownDeveloper** [xavieran/BaKGL#132]
I've done a bit of research into the DAT format.  You can look at my parser for reference.  The only thing I haven't grokked yet is the 'boom' model.

https://github.com/xavieran/BaKGL/blob/0c6a01f9aca18f683226f70b4b841110fe486d57/bak/model.cpp#L211

https://github.com/JasonBrownDeveloper/pyBaK/blob/ebdf7bb90e5d1f3e6acca57981d5e8b07e3157ad/BaK.py#L641

**Comment by xavieran** [comment]
Thanks Jason, I'll have a look.

**Comment by xavieran** [comment]
Related to #3

**Comment by xavieran** [comment]
Hi @JasonBrownDeveloper, thanks for the example code, I've incorporated your suggested modifications into the BaKGL model loading code.

**Comment by JasonBrownDeveloper** [comment]
Glad to share something back, I've picked a couple nuggets from your codebase as well.
