### ISSUE TITLE
Suggestion - Open the graphic format somehow to achieve hi-res packs

### ISSUE THREAD

**Issue by Tormentor667** [xavieran/BaKGL#207]
I wonder if there is a chance to open the gfx-format somehow so people could make hires packs for this project. I am a graphics designer myself and would be very interested in contributing to this.

**Comment by xavieran** [comment]
It's certainly possible,  I can just add support for some other format to the engine. What do you think you would need in order to do this?

The original game uses the following very simple format:
https://github.com/xavieran/BaKGL/blob/master/bak/model.hpp#L71
A list of vertices, then a list of components made up of vertex indices.
The texturing is achieved by giving each face an index into a list of textures, alternatively a face can just have a colour instead.

My own format is the following:
https://github.com/xavieran/BaKGL/blob/master/graphics/meshObject.hpp#L21
And is probably a bit closer to what a modern graphics engine would use.

**Comment by Tormentor667** [comment]
Well I know from for example "Commander Genious" (Commander Keen port) that it reads files from a "mod" folder, that has a "textures" or "hires" folder and checks if there is a replacement file with the same name as the internal graphic.

For example if BaK uses a "GORATH.EXT" image with 100 x 200 pixels for a picture of Gorath, one could place a "GORATH.PNG" (png because it handles alpha as well) image in this folder, with maybe 200 x 400 pixels (or a similar format) that automatically replaces the original image in a higher resoultion or a different look.

Generally, most of the internal graphic patch lump names in BaK should be unique, so this technique could work quite well.

The first step though for you would be to externalize the original graphic patches from the game somehow, so people know which graphics can be replaced and what their name is. Maybe even as a format that can be read natively with common graphic programs (which is doanble if it's already a BMP).

For the 3D meshes (vertices and stuff) I have to admit that I am not used to any 3d designs, so that's up to someone else :)

**Comment by retroindex** [comment]
There are higher resolution character portraits in game manual that may be used ater some rework, also a kingdom map.
![Gorath](https://github.com/user-attachments/assets/511372d5-1a0a-44da-8506-3ddb75753645)

**Comment by xavieran** [comment]
I understand, so you are just referring to the 2d graphics. This should be pretty easy to implement, although I will probably include a few restrictions such as aspect ratio of replacement images must remain the same. It is already possible to replace individual files in both my engine and the original game. I will add a utility for extracting the files from the packed resource file.

**Comment by xavieran** [comment]
I've added two new utilities to the project which may help graphic designers.
`extractor` and `image_extractor`. Extractor unpacks the `krondor.001` file to a directory, and `image_extractor` writes out all the images in the game to BMP format. Note that I am using a simple heuristic for the palettes so you might want to edit the code to add custom mappings from bmx to the corresponding palette files as some images are written out with the wrong palette. I may fix this in the future.

```
extractor -r krondor.001 -i krondor.rmf -o data
image_extractor -r krondor.001 -i krondor.rmf -o images
```

**Comment by xavieran** [comment]
![image](https://github.com/user-attachments/assets/bee8fb25-b1af-413a-8aef-36b6156a36ab)

I'm working on a PR to do this substitution. So far it is pretty straightforward to do.

There will be some complications later with combat, as some enemies simply use the same sprites but with a different color palette (e.g. moredhel spellcasters vs. moredhel warriors).

**Comment by xavieran** [comment]
Merged changes. It is now possible to sub textures used in the 2D and 3D world. 

First extract the images to a mod directory structure using the `image_extractor` utility.
e.g.
```
./image_extractor -r krondor.001 -i krondor.rmf -o mod_dir
```

Then specify the mod directory in the `config.json` file. Copy the file `config.json` from the BaKGL repo root to your `$BAK_DIRECTORY/config.json`. Then update the `/Paths/GraphicsOverrides` key to point to `mod_dir`.

BaKGL will then search in this directory for substitute PNG files. You can replace them with higher res versions as you go.

**Comment by Tormentor667** [comment]
Wow, this implementation was quick. I will try to take a closer look at this next week, I have a full work load in my office until monday, but I can't wait to work on that.

**Comment by Tormentor667** [comment]
**Update**
I noticed that the project needs to be build, as there is no executable. I am not a programmer actually, so I wonder if there is somehow the chance that I get a compiled version for Windows and maybe even an extracted set of graphics from you? From there I could create my replacements and also test the textures/graphics ingame if you can tell me what to do.

Sorry to bother, it's just not something I know how to do :(

**Comment by xavieran** [comment]
I considered this, I've created a windows release here https://github.com/xavieran/BaKGL/releases/tag/0.0.1

This has the main application (main3d) and the image and resource extractor binaries. I've attached instructions on this release and in the main README.MD on setting up mod support, but let me know if there are any issues.

Retroindex was able to set it up but did run into this https://github.com/xavieran/BaKGL/issues/219 so make sure the paths are correct

**Comment by Tormentor667** [comment]
Jus to give you an idea what I am imagining …

![IMG_7615](https://github.com/user-attachments/assets/c09b3371-be93-48d5-b5de-3931bbcf5d77)
![IMG_7616](https://github.com/user-attachments/assets/95a16630-36b8-47c4-a17c-2e3c12c63988)

**Comment by xavieran** [comment]
I assume it's AI? Personally I'm not a big fan of AI art but will be interested to see what you come up with :)

I've done a few experiments with it but have found it difficult to maintain a consistent style over multiple images. Pretty hard to avoid visual defects as well (e.g. the beard growing out from under the armor in this case).

**Comment by Tormentor667** [comment]
Well, it's something we could base our work on. I imagine creating one good base concept, finetuning that and from there creating variants.

**Comment by xavieran** [comment]
I look forward to seeing how it goes :)

I've made a new release today with a few improvements, the game setup is made a bit simpler.
https://github.com/xavieran/BaKGL/releases/tag/0.0.2

Did you have any luck getting 0.0.1 to run with modding support?

**Comment by Tormentor667** [comment]
Very cool, can't waot to check that out. 

Unfortunately not, I have a full workload in my agency lately (same shit every year before Christmas) so it will take 3-4 weeks until I can fully check the modding support. I am eager to play around with it though :)
