### ISSUE TITLE
BaKGL Windows 0.0.1 not working (Win 7/10)

### ISSUE THREAD

**Issue by retroindex** [xavieran/BaKGL#219]
![err](https://github.com/user-attachments/assets/86065cc6-cf8f-4eda-94af-7f49474a1bc3)

D:\BaKGL>main3d
Not loading a config file.
12:56:48.11 INFO [ShaderProgram::LoadFileContents] Loaded precompiled shader contents for file: gui.vert.glsl
12:56:48.11 INFO [ShaderProgram::LoadFileContents] Loaded precompiled shader contents for file: gui.frag.glsl
12:56:48.11 DEBUG [ShaderProgram] Linking shader program: gui.vert.glsl with Id: 3
12:56:48.11 DEBUG [SpriteManager] Adding sprite sheet index: 0
12:56:48.11 WARN [PackedFileDataProvider] Could not find resource index file [krondor.rmf]. Will not use packed resource file for data.
12:56:48.11 FATAL [FileBufferFactory] File not found: OPTIONS.PAL

I'm using floppy version 1.02, krondor.rmf is there:
![files](https://github.com/user-attachments/assets/e3162110-df22-4c45-9e76-12e62e9484f4)

- Empty file main3d.log created in AppData folder

**Comment by retroindex** [comment]
> I think these bak data files should also be in a subfolder data
This solved the problem. Default filenames are fine in subfolder.

**Comment by xavieran** [comment]
Glad to hear, I will make the instructions a bit more clear
