### ISSUE TITLE
Segmentation fault on Ubuntu since commit a20a44f4b00ca0da6f33eacecd0b0c911b1ef8dd

### ISSUE THREAD

**Issue by fredrik-hjarner** [xavieran/BaKGL#233]
I get segmentation fault when trying to run main3d on Ubuntu.

8a3cf8c2f6dce60c702e0ac62f9e7d952463ff6d (master) - segmentation fault
80c7a03f589503b91e93f68b751ca97bab328965 (tag: 0.0.2) - segmentation fault
a20a44f4b00ca0da6f33eacecd0b0c911b1ef8dd - (Issue #68 BaKGL save combatant state (#231)) - segmentation fault
501a2dfbec1993547dfcde31fbda7cd8e8def13e - (Closes #229 Fix audio threading issues (#230)) - works

seems that a20a44f4b00ca0da6f33eacecd0b0c911b1ef8dd made it so.

If I comment out some code in logger.hpp like this then I stop getting seg faults and the game starts and runs without problem:

```
static std::ostream& Log(LogLevel level, const std::string& loggerName)
    {
        // const auto it = std::find(
        //     sDisabledLoggers.begin(), sDisabledLoggers.end(),
        //     loggerName);

        // if (level >= sGlobalLogLevel && it == sDisabledLoggers.end())
        //     return DoLog(level, loggerName);

        return nullStream;
    }
```

I'm building with `./build.sh`
and then running with `./build/main3d` (which seems to load the config.json in root directory)

(btw. looks like you have made great progress, I don't want to be just negative :p)

**Comment by xavieran** [comment]
Thanks for the detailed bug report - I've merged a commit that I think should fix this, however I wasn't able to reproduce the segfault on my own local machine.

Please let me know if you still see a problem here.

**Comment by fredrik-hjarner** [comment]
It is indeed fixed :ok_hand: 

> however I wasn't able to reproduce the segfault on my own local machine.

Interesting differences between systems.
